
    export const products= [
      {
        "id": 1,
        "name": "The Power of HABIT",
        "description": "The Power of HABIT: Why We Do What We Do in Life and Business. A young woman walks into a laboratory. Over the past two years, she has transformed almost every aspect of her life. She has quit smoking, run a marathon, and been promoted at work. The patterns inside her brain, neurologists discover, have fundamentally changed.",
        "price": 16.33,
        "author": "Charles Duhigg",
        "type": "hardcover",
        "img": "https://images-na.ssl-images-amazon.com/images/I/51ejXdSceNL._AA300_.jpg",
        "inCart": false,
        "category": "books"
      },
      {
        "id": 2,
        "name": "Think and Grow Rich",
        "description": "'Think and Grow Rich!' explains entrepreneur Andrew Carnegie’s secret to success, revealed to Napoleon Hill during private interviews with Carnegie, the richest man of his time, and during more than 20 years of research into the lives and philosophies of more than 500 of the most successful people in America. This timeless classic presents a systematic nuts-and-bolts approach to developing the skills and mindset required to achieve exceptional success in any field or endeavor, personal or professional. Hill explains in detail 13 steps required to achieve those goals. The book contains numerous self-tests and checklists.",
        "price": 8.98,
        "author": "Napoleon Hill",
        "type": "hardcover",
        "img": "https://images-na.ssl-images-amazon.com/images/I/51ZouHoBGtL._SX315_BO1,204,203,200_.jpg",
        "inCart": false,
        "category": "books"
      },
      {
        "id": 3,
        "name": "The 7 Habits of Highly Effective People",
        "description": "The 7 Habits of Highly Effective People: Powerful Lessons in Personal Change. The 7 Habits of Highly Effective People, the beloved classic that has sold over 20 million copies worldwide, is celebrating its 25th anniversary with this reissue! With a new foreword, the wisdom of the 7 Habits still holds true after all these years. The 7 Habits have become so famous because they work. They have been integrated into everyday thinking by many millions of people. The reason: They work. Habit 1: Be Proactive. Habit 2: Begin with the End in Mind. Habit 3: Put First Things First. Habit 4: Think Win/Win. Habit 5: Seek First to Understand, Then to Be Understood. Habit 6: Synergize. Habit 7: Sharpen the Saw. The book presents a principle-centered approach for solving personal and professional problems.",
        "price": 11.48,
        "author": "Stephen R. Covey",
        "type": "paperback",
        "img": "https://images-na.ssl-images-amazon.com/images/I/51Myx6jMujL._AA300_.jpg",
        "inCart": false,
        "category": "books"
      },
      {
        "id": 4,
        "name": "Principles: Life and Work",
        "description": "In Principles, Dalio shares what he's learned over the course of his remarkable career. He argues that life, management, economics, and investing can all be systemized into rules and understood like machines.",
        "price": 18.00,
        "author": "Ray Dalio",
        "type": "hardcover",
        "img": "https://images-na.ssl-images-amazon.com/images/I/51UyMOpP%2BGL._AA300_.jpg",
        "inCart": false,
        "category": "books"
      },
      {
        "id": 5,
        "name": "How to Win Friends & Influence People",
        "description": "For more than sixty years the rock-solid, time-tested advice in this book has carried thousands of now famous people up the ladder of success in their business and personal lives. Now this previously revised and updated bestseller is available in trade paperback for the first time to help you achieve your maximum potential throughout the next century!",
        "price": 9.60,
        "author": "Dale Carnegie",
        "type": "paperback",
        "img": "https://images-na.ssl-images-amazon.com/images/I/51PWIy1rHUL._AA300_.jpg",
        "inCart": false,
        "category": "books"
      },
      {
        "id": 6,
        "name": "The Whole 30",
        "description": "Since 2009, Melissa Hartwig’s critically-acclaimed Whole30 program has quietly led hundreds of thousands of people to effortless weight loss and better health—along with stunning improvements in sleep quality, energy levels, mood, and self-esteem. The program accomplishes all of this by specifically targeting people’s habits and emotional relationships with food. The Whole30 is designed to help break unhealthy patterns of behavior, stop stress-related comfort eating, and reduce cravings, particularly for sugar and carbohydrates. Many Whole30 participants have described achieving 'food freedom'—in just thirty days.",
        "price": 18.00,
        "author": "Melissa Hartwig",
        "type": "hardcover",
        "img": "https://images-na.ssl-images-amazon.com/images/I/61WFjEDBktL._SX437_BO1,204,203,200_.jpg",
        "inCart": false,
        "category": "books"
      },
      {
        "id": 7,
        "name": "The Food Lab",
        "description": "Ever wondered how to pan-fry a steak with a charred crust and an interior that's perfectly medium-rare from edge to edge when you cut into it? How to make homemade mac 'n' cheese that is as satisfyingly gooey and velvety-smooth as the blue box stuff, but far tastier? How to roast a succulent, moist turkey (forget about brining!)―and use a foolproof method that works every time?",
        "price": 33.94,
        "author": "J. Kenji López-Alt",
        "type": "harcover",
        "img": "https://images-na.ssl-images-amazon.com/images/I/419aGgQt-5L._SX392_BO1,204,203,200_.jpg",
        "inCart": false,
        "category": "books"
      },
      {
        "id": 10,
        "name": "True Fiction (Ian Ludlow Thrillers)",
        "description": "A breakneck thriller where truth and fiction collide for the unluckiest writer alive.",
        "price": 4.99,
        "author": "Lee Goldberg",
        "type": "kindle",
        "img": "https://images-na.ssl-images-amazon.com/images/I/51UbplnqSgL._SX331_BO1,204,203,200_.jpg",
        "inCart": false,
        "category": "books"
      },
      {
        "id": 11,
        "name": "The Last Move",
        "description": "An FBI agent must catch a copycat killer. The only difference this time: she's the final victim.",
        "price": 7.91,
        "author": "Mary Burton",
        "type": "paperback",
        "img": "https://images-na.ssl-images-amazon.com/images/I/514jRDA21TL._AA300_.jpg",
        "inCart": false,
        "category": "books"
      },
      {
        "id": 12,
        "name": "Stillhouse Lake (Stillhouse Lake Series)",
        "description": "Gina Royal is the definition of average—a shy Midwestern housewife with a happy marriage and two adorable children. But when a car accident reveals her husband’s secret life as a serial killer, she must remake herself as Gwen Proctor—the ultimate warrior mom.",
        "price": 8.96,
        "author": "Rachel Caine",
        "type": "paperback",
        "img": "https://images-na.ssl-images-amazon.com/images/I/41RTt7alEqL._SX332_BO1,204,203,200_.jpg",
        "inCart": false,
        "category": "books"
      },
      {
        "id": 16,
        "name": "Harry Potter and the Sorcerer's Stone",
        "description": "On Harry's eleventh birthday, a great beetle-eyed giant of a man called Rubeus Hagrid bursts in with some astonishing news: Harry Potter is a wizard, and he has a place at Hogwarts School of Witchcraft and Wizardry. An incredible adventure is about to begin!",
        "price": 24.64,
        "author": "J.K.Rowling",
        "type": "hardcover",
        "img": "https://images-na.ssl-images-amazon.com/images/I/51qlgJ6ZojL.jpg",
        "inCart": false,
        "category": "books"
      },
      {
        "id": 17,
        "name": "A Game of Thrones: A Song of Ice and Fire, Book 1",
        "description": "As a whole, this series comprises a genuine masterpiece of modern fantasy, bringing together the best the genre has to offer. Magic, mystery, intrigue, romance, and adventure fill these pages and transport us to a world unlike any we have ever experienced.",
        "price": 25.16,
        "author": "George R. R. Martin",
        "type": "hardcover",
        "img": "https://images-na.ssl-images-amazon.com/images/I/51n5SAiAz7L._AA300_.jpg",
        "inCart": false,
        "category": "books"
      },
      {
        "id": 18,
        "name": "The Lord of the Rings: One Volume",
        "description": "In ancient times the Rings of Power were crafted by the Elven-smiths, and Sauron, the Dark Lord, forged the One Ring, filling it with his own power so that he could rule all others.",
        "price": 27.66,
        "author": "J.R.R. Tolkien",
        "type": "hardcover",
        "img": "https://images-na.ssl-images-amazon.com/images/I/51d4G0sFMzL.jpg",
        "inCart": false,
        "category": "books"
      },
      {
        "id": 19,
        "name": "AWG Men's Cotton Regular Fit Solid Polo Neck T-Shirt",
        "description": "This T-shirt is made of Cotton fabric and gives utmost comfort during all temperatures. Elegant stitch and Solid colours maked this T-shirt a perfect Formal and Casual wear. ",
        "price": 12,
        "author": "J.R.R. Tolkien",
        "type": "hardcover",
        "img": "https://m.media-amazon.com/images/I/616735yPw2L._UX569_.jpg",
        "inCart": false,
        "category": "clothes"
      },
      {
        "id": 20,
        "name": "Van Heusen Athleisure Men's Regular fit T-Shirt",
        "description": "This mens signature 100% cotton everyday essential tshirt comes with Virotech™ feature which keeps you protected from various microbes.",
        "price": 15,
        "author": "J.R.R. Tolkien",
        "type": "hardcover",
        "img": "https://m.media-amazon.com/images/I/71PofKud5OL._UX522_.jpg",
        "inCart": false,
        "category": "clothes"
      },
      {
        "id": 21,
        "name": "Scott International Men's Regular Fit T-Shirt (Pack of 3)",
        "description": "This mens signature 100% cotton everyday essential tshirt comes with Virotech™ feature which keeps you protected from various microbes.",
        "price": 15,
        "author": "J.R.R. Tolkien",
        "type": "hardcover",
        "img": "https://m.media-amazon.com/images/I/71vp8Lec9JL._UX679_.jpg",
        "inCart": false,
        "category": "clothes"
      },
      {
        "id": 22,
        "name": "Saiyaara Fashion Women's Cotton Embroidery Salwar Suit",
        "description": "Saiyaara Fashion Women's Cotton Embroidery Salwar Suit Dupatta Material Maroon, Free Size",
        "price": 15,
        "author": "J.R.R. Tolkien",
        "type": "hardcover",
        "img": "https://m.media-amazon.com/images/I/71fxQbDWMBL._UX679_.jpg",
        "inCart": false,
        "category": "clothes"
      },
      {
        "id": 23,
        "name": "Miraan Cotton Printed Readymade Salwar Suit",
        "description": "Miraan Cotton Printed Readymade Salwar Suit For Women(MIRAANSAN2311, Multi-Coloured)",
        "price": 15,
        "author": "J.R.R. Tolkien",
        "type": "hardcover",
        "img": "https://m.media-amazon.com/images/I/91v1G2rhkpL._UY741_.jpg",
        "inCart": false,
        "category": "clothes"
      },
      {
        "id": 24,
        "name": "Nivah Fashion Women's Georgette",
        "description": "Nivah Fashion Women's Georgette Embroidery Dress Material with Heavy Work Dupatta",
        "price": 15,
        "author": "J.R.R. Tolkien",
        "type": "hardcover",
        "img": "https://m.media-amazon.com/images/I/811t0NXMT2L._UY741_.jpg",
        "inCart": false,
        "category": "clothes"
      },
      {
        "id": 25,
        "name": "Nature's Nectar Raw Organic Honey 400g",
        "description": "Nature's Nectar Raw Organic Honey 400g | 100% Pure NMR Tested Honey | Raw and Unprocessed | NPOP Certified Organic By Lacon",
        "price": 15,
        "author": "J.R.R. Tolkien",
        "type": "hardcover",
        "img": "https://m.media-amazon.com/images/I/71+0go92jeS._SX679_.jpg",
        "inCart": false,
        "category": "groceries"
      },
      {
        "id": 26,
        "name": "Behnam Premium 3A Quality Afghani Mamra Giri Badam / Almonds - 500 Gram",
        "description": "Nature's Nectar Raw Organic Honey 400g | 100% Pure NMR Tested Honey | Raw and Unprocessed | NPOP Certified Organic By Lacon",
        "price": 15,
        "author": "J.R.R. Tolkien",
        "type": "hardcover",
        "img": "https://m.media-amazon.com/images/I/81uQpG9yCAL._SX679_.jpg",
        "inCart": false,
        "category": "groceries"
      },
      {
        "id": 27,
        "name": "Tata Sampann 100% Pure Premium Cashews Whole, 200g",
        "description": "Introducing, new Tata Sampann Premium Cashews (Whole)! Each pack contains the choicest selection of handpicked nuts with a promise to consistently deliver premium quality. Enjoy 100% pure Premium Cashews that are crunchy, flavourful, and of uniform colour and deluxe size.",
        "price": 15,
        "author": "J.R.R. Tolkien",
        "type": "hardcover",
        "img": "https://m.media-amazon.com/images/I/61BvOiNj62L._SX679_.jpg",
        "inCart": false,
        "category": "groceries"
      },
      {
        "id": 28,
        "name": "Fitness Mantra Ayurvedic Wheat Grass Juice Bottle, 1 L",
        "description": "Size: 450 gm how can we use: - rinse quinoa in a sieve under water. Place the quinoa and water in a saucepan and bring to the boil. Reduce heat to low. Cover with lid and simmer until most of the liquid has been absorbed -- between 12-15 minutes. Remove from heat",
        "price": 15,
        "author": "J.R.R. Tolkien",
        "type": "hardcover",
        "img": "https://m.media-amazon.com/images/I/512z64h66+L._SX679_.jpg",
        "inCart": false,
        "category": "groceries"
      },
      {
        "id": 29,
        "name": "Fortune Rozana Basmati Rice, suitable for daily cooking, 5 kg",
        "description": "Fortune Rozana basmati rice is a fine variety of basmati that you can relish every day. It is specially aged to help every grain acquire the best basmati characteristics of fluffy and long grain. On cooking, the grains do not stick together and become flavorsome. ",
        "price": 15,
        "author": "J.R.R. Tolkien",
        "type": "hardcover",
        "img": "https://m.media-amazon.com/images/I/614FVJNeAOL._SX679_.jpg",
        "inCart": false,
        "category": "groceries"
      },
      {
        "id": 30,
        "name": "Daawat Rozana Super, Naturally Aged, Rich Aroma,Perfect Fit for Everyday Consumption Basmati Rice, 5 Kg",
        "description": "Daawat rozana super is the finest basmati rice in the mid-price segment. It is specially processed for daily cooking across a multitude of regular dishes, a perfect fit for every day consumption. Rozana super promises a sweet taste and rich aroma as each grain is naturally aged.",
        "price": 15,
        "author": "J.R.R. Tolkien",
        "type": "hardcover",
        "img": "https://m.media-amazon.com/images/I/810jp1zceeL._SY741_.jpg",
        "inCart": false,
        "category": "groceries"
      },
      {
        "id": 31,
        "name": "Tata Sampann Unpolished Toor Dal/ Arhar Dal, 1kg",
        "description": "Tata Sampann Toor dal is unpolished as it does not undergo any artificial polishing with water, oil or leather thereby retaining its goodness and wholesomeness.The 5-step process ensures that Tata Sampann Toor dal grains are uniform and of premium quality, giving you an all-natural, authentic taste.",
        "price": 10,
        "author": "J.R.R. Tolkien",
        "type": "hardcover",
        "img": "https://m.media-amazon.com/images/I/71hFwEGKyZL._SX679_.jpg",
        "inCart": false,
        "category": "groceries"
      }
    ]
  